#Distance in sign without distance insert on sign
defaultdistance: 200

#Aspect of Signs
line1: "&c[RandomTP]"
line2: "&2%distance"

#Messages
message: "&c[RandomTP] &aSei stato teletrasportato con successo"