name: Randomteleport
version: '${project.version}'
main: randomteleport.randomteleport.Randomteleport
api-version: 1.19
authors: [ aushot ]
description: RandomTeleport
website: 'https://github.com/aushot'